name: Docker Workflow

on: 
  push:
    branches: [main]

env: 
  DOCKERHUB_USERNAME: lorenzo1100
  DOCKERHUB_REPOSITORY: hello-world

jobs:
  lint_node_application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
        
      - name: Lint
        run: npm run lint

  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        

      - name: Dockerhub Authentication
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      
      - name: Build and push docker image
        run: | 
          docker build . -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}: ${{ github.sha }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}: ${{ github.sha }}
        