name: Docker Buildd,Lint & Push CI

on: 
  push:
    branches: [main]

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_REPOSITORY: hello-world
jobs:
  lint_node_application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          npm install
        
      - name: Lint
        run: npm run lint

  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        

      - name: Dockerhub Authentication
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
        
      
      - name: Build and push docker image
        run: | 
          docker build . -t $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY
          docker push $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY
        
